# Offense count: 4
Metrics/AbcSize:
  Max: 29

# Offense count: 1
Metrics/CyclomaticComplexity:
  Max: 12

# Offense count: 5
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 154

# Offense count: 3
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 13

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 10

# Offense count: 1
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/git_log_stats.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/EmptyLines:
  Exclude:
    - 'lib/log_analyzer.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: empty_lines, no_empty_lines
Style/EmptyLinesAroundBlockBody:
  Exclude:
    - 'git_log_stats.gemspec'
    - 'lib/log_analyzer.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles, UseHashRocketsWithSymbolValues, PreferHashRocketsForNonAlnumEndingSymbols.
# SupportedStyles: ruby19, hash_rockets, no_mixed_keys, ruby19_no_mixed_keys
Style/HashSyntax:
  EnforcedStyle: hash_rockets

# Offense count: 1
# Cop supports --auto-correct.
Style/MutableConstant:
  Exclude:
    - 'lib/git_log_stats/version.rb'


# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'Rakefile'
    - 'lib/git_log_stats/version.rb'
